the_coffee_lover:
  host: the-coffee-bar
  port: 8082
  agent_host: jaeger
  agent_port: 6831
  service_name: the-coffee-lover
  log_level: info
the_coffee_bar:
  host: the-coffee-bar
  port: 8082
  coffeemachine_host: the-coffee-machine
  coffeemachine_port: 8083
  cashdesk_host: the-cashdesk
  cashdesk_port: 8084
  agent_host: jaeger
  agent_port: 6831
  service_name: the-coffee-bar
  log_level: info
the_coffee_machine:
  host: the-coffee-machine
  port: 8083
  agent_host: jaeger
  agent_port: 6831
  service_name: the-coffee-machine
  log_level: info
the_cashdesk:
  host: the-cashdesk
  port: 8084
  agent_host: jaeger
  agent_port: 6831
  service_name: the-cashdesk
  connection_string: postgresql://account:account@postgres:5432/account
  log_level: info
