version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  the-coffe-bar:
    image: sumo/python-the-coffee-bar-app
    container_name: the-coffee-bar
    hostname: the-coffee-bar
    ports:
      - 8082:8082
    expose:
      - 8082
    command: ["opentelemetry-instrument", "python3", "src/bin/the_coffee_bar.py", "--config=src/config/config.yaml"]
  the-coffee-machine:
    image: sumo/python-the-coffee-bar-app
    container_name: the-coffee-machine
    hostname: the-coffee-machine
    ports:
      - 8083:8083
    command: ["opentelemetry-instrument", "python3", "src/bin/the_coffee_machine.py", "--config=src/config/config.yaml"]
  the-cashdesk:
    image: sumo/python-the-coffee-bar-app
    container_name: the-cashdesk
    hostname: the-cashdesk
    ports:
      - 8084:8084
    command: ["opentelemetry-instrument", "python3", "src/bin/the_cashdesk.py", "--config=src/config/config.yaml"]
#  the-coffee-lover:
#    image: sumo/python-the-coffee-bar-app
#    container_name: the-coffee-lover
#    hostname: the-coffee-lover
#    command: ["python", "src/bin/the_coffee_lover.py", "--config=src/config/config.yaml"]
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    hostname: jaeger
    ports:
      - "6831:6831/udp"
      - "9411:9411"
      - "16686:16686"
    expose:
      - 16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
